// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Fall back to the local SQLite file when DATABASE_URL is not provided
    // (e.g. CI/Vercel builds where no .env is present) so `prisma migrate
    // deploy` in the build step does not fail. This mirrors .env.example and
    // the runtime client in src/lib/prisma.ts, which always uses ./dev.db.
    url: process.env["DATABASE_URL"] ?? "file:./dev.db",
  },
});
